---
title: "Linear Models"
author: "Jieqi Tu (jt3098)"
date: "12/11/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(leaps)
```

## Import and tidy data
```{r import data}
# Import data
cancer_raw = readr::read_csv("./Data/Cancer_Registry.csv") %>% 
  janitor::clean_names() 

dim(cancer_raw)
head(cancer_raw)

# Check NA values for each column
n_NA = sapply(cancer_raw[1:34], function(x) sum(length(which(is.na(x)))))
n_NA

# Check the percentage of NA values for each column
percentage_NA = sapply(cancer_raw[1:34], function(x) sum(length(which(is.na(x)))) / 3047)
percentage_NA %>% data.frame()

#Pulling quartiles for study_per_cap categorical manipulation
study.quart <- with(cancer_raw, study_per_cap[study_per_cap > 0]) %>%
  quantile(., probs = c(0.25, 0.5, 0.75))

#Variable Manipulation
cancer.df <- cancer_raw %>%    #Remove Rows with > 20% missing 
  dplyr::select(-pct_some_col18_24) %>%  #Remove for too many missing
  mutate(
    pct_non_white = pct_black + pct_asian + pct_other_race, #Creating white, non-white percentages variables
    state = str_split_fixed(geography, ", ", 2)[ ,2] %>% as.factor(), #pulling state variable and casting as factor, possible region?
    binned_inc_lb = str_split_fixed(binned_inc, ", ", 2)[ ,1] %>% parse_number(), #pulling numeric lower bound
    binned_inc_ub = str_split_fixed(binned_inc, ", ", 2)[ ,2] %>% parse_number(), #pulling numeric upper bound
    binned_inc_point = (binned_inc_lb + binned_inc_ub)/2, #computing point estimate from ub,lb (intervals symmetric)
    study_quantile = ifelse(study_per_cap == 0, "None", 
                           ifelse(study_per_cap > 0 & study_per_cap <= study.quart[1], "Low", 
                                  ifelse(study_per_cap > study.quart[1] & study_per_cap <= study.quart[2], "Moderate", 
                                         ifelse(study_per_cap > study.quart[2] & study_per_cap <= study.quart[3], "High", 
                                                "Very High")))),
    study_quantile = as.factor(study_quantile) %>% fct_relevel(., "None", "Low", "Moderate", "High", "Very High"),
    avg_deaths_yr_pop = avg_deaths_per_year/pop_est2015,  #incorporate two vars into one (multicollinearity)
    avg_ann_count_pop = avg_ann_count/pop_est2015 #incorporate two vars into one (multicollinearity)
  ) %>%
  dplyr::select(-c(binned_inc, geography, study_per_cap))

# Variable Manipulation: Add region classification 
table(cancer.df$state)  

# create a dataframe containing all the 4-level states names
NE.name <- c("Connecticut","Maine","Massachusetts","New Hampshire",
             "Rhode Island","Vermont","New Jersey","New York",
             "Pennsylvania")
MW.name <- c("Indiana","Illinois","Michigan","Ohio","Wisconsin",
             "Iowa","Kansas","Minnesota","Missouri","Nebraska",
             "North Dakota","South Dakota")
S.name <- c("Delaware","District of Columbia","Florida","Georgia",
            "Maryland","North Carolina","South Carolina","Virginia",
            "West Virginia","Alabama","Kentucky","Mississippi",
            "Tennessee","Arkansas","Louisiana","Oklahoma","Texas")
W.name <- c("Arizona","Colorado","Idaho","New Mexico","Montana",
            "Utah","Nevada","Wyoming","Alaska","California",
            "Hawaii","Oregon","Washington")

region.list <- list(
  Northeast = NE.name,
  Midwest = MW.name,
  South = S.name,
  West = W.name)

#create new region variable identical to 'region'
cancer.df$region <- sapply(cancer.df$state, 
                 function(x) names(region.list)[grep(x,region.list)])     
#relevelnumber of countries by region (original variable) 

cancer.clean = cancer.df %>% as.data.frame()

cancer.clean = 
  cancer.clean %>% 
  select(pct_white, pct_hs25_over, pct_employed16_over, pct_private_coverage, pct_public_coverage, target_death_rate, avg_ann_count_pop, avg_household_size, avg_deaths_yr_pop, med_income, median_age_male, median_age_female, region, study_quantile) %>% 
  mutate(median_age_all_gender = (median_age_male + median_age_female)/2) %>% 
  mutate(south = ifelse(region == "South", 1, 0)) %>% 
  select(-median_age_female, -median_age_male, -region) %>% 
  mutate(study_quantile = as.factor(study_quantile))
# Select variables that we are interested in
  
```

## Variable Selection

Automatic procedures:
(1) Backward:
```{r backward procedure}
mult.fit = lm(target_death_rate ~ ., data = cancer.clean)
summary(mult.fit)

# Remove the variable with the highest p-value: avg_household_size
step1 = update(mult.fit, . ~ . -avg_household_size)
summary(step1)

# All variables are significant with p-value less than 0.05

# store the result of backward procedure
model_backward = step1
```

(2) Forward:
```{r forward procedure}
# check p-value for each predictor in SLR model
fit1 = lm(target_death_rate ~ pct_white, data = cancer.clean)
tidy(fit1)
fit2 = lm(target_death_rate ~ pct_hs25_over, data = cancer.clean)
tidy(fit2)
fit3 = lm(target_death_rate ~ pct_employed16_over, data = cancer.clean)
tidy(fit3)
fit4 = lm(target_death_rate ~ pct_private_coverage, data = cancer.clean)
tidy(fit4)
fit5 = lm(target_death_rate ~ pct_public_coverage, data = cancer.clean)
tidy(fit5)
fit6 = lm(target_death_rate ~ avg_ann_count_pop, data = cancer.clean)
tidy(fit6)
fit7 = lm(target_death_rate ~ avg_deaths_yr_pop, data = cancer.clean)
tidy(fit7)
fit8 = lm(target_death_rate ~ med_income, data = cancer.clean)
tidy(fit8)
fit9 = lm(target_death_rate ~ study_quantile, data = cancer.clean)
tidy(fit9)
fit10 = lm(target_death_rate ~ median_age_all_gender, data = cancer.clean)
tidy(fit10)
fit11 = lm(target_death_rate ~ avg_household_size, data = cancer.clean)
tidy(fit11)
fit12 = lm(target_death_rate ~ south, data = cancer.clean)
tidy(fit12)

# start with one predictor that has the lowest p-value: avg_deaths_yr_pop
step1 = lm(target_death_rate ~ avg_deaths_yr_pop, data = cancer.clean)
tidy(step1)

# enter the one with the lowest p-value in the rest
step2 = update(step1, .~. + med_income)
tidy(step2)
step3 = update(step2, .~. + pct_hs25_over)
tidy(step3)
step4 = update(step3, .~. + pct_public_coverage)
tidy(step4)
step5 = update(step4, .~. + pct_employed16_over)
tidy(step5)
step6 = update(step5, .~. + pct_private_coverage)
tidy(step6)
step7 = update(step6, .~. + south)
tidy(step7)
step8 = update(step7, .~. + pct_white)
tidy(step8)
step9 = update(step8, .~. + study_quantile)
tidy(step9)
step10 = update(step9, .~. + avg_ann_count_pop)
tidy(step10)
step11 = update(step10, .~. + avg_household_size)
tidy(step11)
step12 = update(step11, .~. + median_age_all_gender)
tidy(step12)

# store the result of forward procedure
model_forward = step12
```

(3) stepwise procedure
```{r stepwise procedure}
# use stepwise function to choose the best subsets
step(mult.fit, direction = "backward")

# store the result of stepwise procedure
model_stepwise = lm(target_death_rate ~ pct_white + pct_hs25_over + 
    pct_employed16_over + pct_private_coverage + pct_public_coverage + 
    avg_ann_count_pop + avg_deaths_yr_pop + med_income + study_quantile + 
    median_age_all_gender + south, data = cancer.clean)
```

Test-based procedures:
```{r test-based procedures}
# generate test results and plot
criteria_results <- (leaps::regsubsets(data = cancer.clean, target_death_rate ~.) %>% summary())
tibble(
  n_pred = c(1:8),
  "Cp" = criteria_results$cp,
  "RSQ" = criteria_results$rsq,
  "RSS" = criteria_results$rss,
  "BIC" = criteria_results$bic
) %>% gather(key = "Statistics", value = "value", 2:5) %>%
  ggplot(aes(x = n_pred, y = value)) +
  geom_point() +
  geom_line() +
  facet_grid(Statistics ~ ., scales = "free_y") +
  theme_bw()
```

